Урок 2.Практическое задание 1

1. Установите, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найдите размерности полученных матриц:

а)  𝐴  — матрица  4×2 ,  𝐵  — матрица  4×2 ;

б)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3 ;

в)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8 ;

г)  𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4 .

Dариант a:

 A * B = 4 * 2  и 4 * 2

  B * A = 4 * 2  и 4 * 2

Произведения не определены

Вариант б:

A * B = 2 * 5  и 5 * 2 , произведение определено, размерность полученной матрицы 2 X 3

B * A = 5 * 3  и 2 * 5 , произведение не определено

Вариант в:

 A * B = 8 * 3  и 3 * 8 , произведение определено, размерность полученной матрицы 8 X 8

 B * A = 3 * 8  и 8 * 3 , произведение определено, размерность полученной матрицы 3 X 3

Вариант г:

A * B , B * A - оба произведения определены, размерность полученной матрицы 4 X 4

2. Найдите сумму и произведение матриц 𝐴=(1 −2)    𝐵=(4 −1)
                                          3  0   и    0  5

In [1]:
import numpy as np

In [2]:
a = np.array([[1,-2], [3,0]])
b = np.array([[4,-1], [0,5]])
result2_1 = a + b
result2_1

array([[ 5, -3],
       [ 3,  5]])

In [3]:
result2_2 = np.dot(a, b)
result2_2

array([[  4, -11],
       [ 12,  -3]])

3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию  3𝐴−2𝐵+4𝐶  для матриц  𝐴=(1  7)   𝐵=(0  5)   𝐶=(2  −4)
                                                                       3 −6 ,     2 −1  ,    1   1.

In [4]:
a = np.array([[1,7], [3,-6]])
b = np.array([[0,5], [2,-1]])
c = np.array([[2,-4], [1,1]])
result3 = (3 * a) + (-2 * b) + (4 * c)
result3

array([[ 11,  -5],
       [  9, -12]])

4. Дана матрица  𝐴=(4  1
                 5 -2
                 2  3) . Вычислите  𝐴𝐴^𝑇  и  𝐴^𝑇𝐴 .

In [5]:
a = np.array([[4,1], [5,-2], [2,3]])
aT = a.T
aT

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [6]:
result4_1 = np.dot(a, aT)
result4_1

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [7]:
result4_2 = np.dot(aT, a)
result4_2

array([[45,  0],
       [ 0, 14]])

5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [8]:
def multiply_matrix(matrix1, matrix2):
    if len(matrix1[0]) != len(matrix2):
        return ValueError('произведение не определено')
    result = [ [0 for j in range(len(matrix2[0]))] for i in range(len(matrix1))]
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    return result

проверка

In [9]:
x = np.array([[1,-2], [3,0], [5,7]])
y = np.array([[4,-1], [0,5]])
print(f'Матрица Х:\n {x}')
print(f'Матрица Y:\n {y}')
print(f'Результат метода NumPy:\n {np.dot(x,y)}')
print(f'Результат собственного метода: \n {multiply_matrix(x,y)}')

Матрица Х:
 [[ 1 -2]
 [ 3  0]
 [ 5  7]]
Матрица Y:
 [[ 4 -1]
 [ 0  5]]
Результат метода NumPy:
 [[  4 -11]
 [ 12  -3]
 [ 20  30]]
Результат собственного метода: 
 [[4, -11], [12, -3], [20, 30]]


Урок 2.Практическое задание 2

1. Вычислите определитель:
a) |sinx  -cosx|
    cosx   sinx

det=sinx*sinx-(cosx-cosx)=sin^2x-cos^2x

б) |4  2  3
    0  5  1
    0  0  9|

In [10]:
a1_2 = np.array([[4,2,3], [0,5,1], [0,0,9]])
det1_2 = np.linalg.det(a1_2)
det1_2

180.0

в)  |1  2  3
     4  5  6
     7  8  9|

In [11]:
a1_3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
det1_3 = np.linalg.det(a1_3)
det1_3

0.0

2. Определитель матрицы  𝐴  равен  4 . Найдите:

а)  𝑑𝑒𝑡(𝐴^2) ;

б)  𝑑𝑒𝑡(𝐴^𝑇) ;

в)  𝑑𝑒𝑡(2𝐴) .


a) 𝑑𝑒𝑡(𝐴^2)=det(AA)=det(A)*det(a)=4*4=16
b) 𝑑𝑒𝑡(𝐴^𝑇)=det(A)=4
в) 𝑑𝑒𝑡(2𝐴)=det(A)*2^n=4*2^n, где  n - кол-во строк в матрице

3. Докажите, что матрица:  
    |-2  7 -3
      4 14  6
     -3  7  13| вырожденная

In [12]:
a3 = np.array([[-2,7,-3], [4,-14,6], [-3,7,13]])
det3 = np.linalg.det(a3)
det3

0.0

определитель матрицы равен нулю, следовательно, матрица вырожденная

4. Найти ранг матрицы:
а) |1  2  3
    1  1  1
    2  3  4|
    

In [13]:
a4_1 = np.array([[1,2,3], [1,1,1], [2,3,4]])
result4_1 = np.linalg.matrix_rank(a4_1)
result4_1

2

б) |0  0  2  1
    0  0  2  2
    0  0  4  3
    2  3  5  6|

In [14]:
a4_2 = np.array([[0,0,2,1], [0,0,2,2], [0,0,4,3], [2,3,5,6]])
result4_2 = np.linalg.matrix_rank(a4_2)
result4_2

3

Урок 3.Практическое задание 

1. Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей
 
 A= (-1  -6
      2   6)
 

|-1-L  -6
  2    6-L| = 0
    
 (-1-L)*(6-L)- 2*(-6)
L^2-5L+6=0
D=5^2-4*1*6=1
L1=(5+1)/2=3
L2=(5-1)/2=2

Найдем собственные векторы для  система уравнений будет выглядеть:

{-x1-6x^2=2x1
 2x1+6x2=2x2
 
 Перенеся все в левую часть, получим
 {3x1-6x2=0
  2x1+4x2=0
  
  {x2=-x1/2
   0=0
   
  Найдем собственные векторы для  система уравнений будет выглядеть:
  
  {-x1-6x2=0
   -2x1+3x2=0
   
 {x2=-2x1/3
   0=0

In [15]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


2. Дан оператор поворота на 180 градусов, задаваемый матрицей

 A= (-1   0
      0  -1)
      
 Показать, что любой вектор является для него собственным.

|-1-L    0
  0    -1-L| = 0
    
-1*L^2=0
L^2+2L+1=0
D=2^2-4*1*1=0
L=-2/2=-1

Найдем собственные векторы вида (x1
                                 x2) и система уравнений будет выглядеть:
    
     (-1   0    (x1   = L (x1
      0  -1) *   x2)       x2)
        
        {1=-1*x1+0*x2=-1*x1
         0*x1+(-1)*x2=-1*x2
         
        {-x1=-x1
         -x2=-x2
         
        {0=0
         0=0
         
Следовательно, любой вектор является для данного оператора поворота будет собственным

3. Пусть линейный оператор задан матрицей

A= (1  1
   -1  3)
Установить, является ли вектор  x= (1,1) собственным вектором этого линейного оператора.


Предположим, что вектор  является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число L, при котором

 (1  1    (1   = L (1
 -1  3) *  1)       1)
 
 Из этого будет следовать, что
 
  {1+1=L   [L=2
  -1+3=L    L=2
  Следовательно, вектор x= (1,1) является собственным вектором линейного оператора, заданного матрицей A

4. Пусть линейный оператор задан матрицей

A= (0  3  0
    3  0  0
    0  0  3)
    
   Установить, является ли вектор x= (3,-3, -4) собственным вектором этого линейного оператора.


Предположим, что вектор x является собственным вектором заданного линейного оператора. Тогда получим:
    (0  3  0    (3         (3
     3  0  0 *  -3   = L   -3
     0  0  3)   -4)        -4)
    
    {L=-3
     L=-3
     L=3
   Такая система не имеет смысла, следовательно, вектор x= (3,-3, -4) не является собственным вектором линейного оператора, заданного матрицей A.